### ISSUE TITLE
Support of Maplibre

### ISSUE THREAD

**Issue by blackrez** [ankane/mapkick.py#2]
Hello,

I really like the idea. Do you know if is possible to use Maplibre https://maplibre.org/ instead of mapbox GL. Mapbox GL is not really opensource now. 

For more explainations :

https://www.maptiler.com/news/2021/01/mapbox-gl-open-source-fork/

**Comment by ankane** [comment]
Hey @blackrez,

1. The Mapkick bundle (`mapkick.bundle.js`) uses Mapbox GL JS v1, which is open source
2. You can use MapLibre, but need to include the JavaScript files for it and Mapkick.js manually - [instructions here](https://github.com/ankane/mapkick.js#maplibre)

**Comment by blackrez** [comment]
Nice to see, thanks a lot.
